spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:  731364585730-c65kpnevooef2boo5s1takl3i5ogrdbl.apps.googleusercontent.com
            clientSecret: e384n49S7d2QO2dvi64VXQxp
            redirectUri: "http://localhost:8080/oauth2/callback/{registrationId}"
            #redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the frontend client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect